### ISSUE TITLE
Clarify how to manage Deepgram subscriptions and connections

### ISSUE THREAD

**Issue by AndryHTC** [tempo-riz/deepgram_speech_to_text#1]
Hi there! First of all, great job!

I have a few questions about managing subscriptions and connections when using the Deepgram package:

1. Is there a way to manually close the subscriptions created inside the Deepgram package, or does the package automatically handle subscription management in some way?
2. For example, when using `deepgram.transcribeFromLiveAudioStream`, it listens to the Audio Stream to create a String Stream. However, it's not clear how the connection is handled and disposed of. Could you provide more details on this?
3. Is there a way to pause the connection to Deepgram and start it again later? I'd like to avoid using credits when the app is idle.

Any clarification or guidance on these topics would be greatly appreciated. Let me know if you need any additional information!

Thanks in advance.

**Comment by tempo-riz** [comment]
Hey ! Thanks it's my first dart package, doing my best :)
For data streaming you have 2 options : 
- first the `deepgram.transcribeFromLiveAudioStream`  as you said which takes an input audio stream and outputs and json stream. Here the connection is created once you call the method, if the input stream or the result stream (websocket) from deepgram's server is closed, the json stream will close itself automatically.
- If you want more control over the stream you can also use the `deepgram.createLiveTranscriber`  which you can use like this : 
```
final DeepgramLiveTranscriber transcriber = deepgram.createLiveTranscriber(audioStream);

  transcriber.start();

  transcriber.jsonStream.listen((json) {
    print(json);
  });
  transcriber.close();
```
for now there is not pause method, but you shouldn't need it since calling start() will restart the connection, so you can for example : 
- create the transcriber once
- then start() it, and once you want to stop the stream close() it, but you can call start() again after that without problem !

About using credits, both of these methods only send data when there is data in the audio stream, so let's say you are recording from a mic, if you pause/stop the record no data will be send to deepgram !

Hope it helps :) Feel free to ask if you need more clarifications
